apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare
data:
  config.yml: |
    tunnel: temporal-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json

    ingress:
      # Forward all traffic to Traefik
      - hostname: "*.tikalabs.dev"
        service: http://traefik.traefik.svc.cluster.local:80
      - hostname: tikalabs.dev
        service: http://traefik.traefik.svc.cluster.local:80
      # Catch-all for any other traffic
      - service: http_status:404

